name: Source Code Frontend CD

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t sourcecode-front .
      - name: Tags
        run: |
          docker tag sourcecode-front ${{ secrets.DOCKER_USER }}/sourcecode-front:${{ github.sha }}
          docker tag sourcecode-front ${{ secrets.DOCKER_USER }}/sourcecode-front:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/sourcecode-front:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/sourcecode-front:latest
